# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170123_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_list', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
